### ISSUE TITLE
InputPrompt string not shown

### ISSUE THREAD

**Issue by isccarrasco** [Ansku/numberfield#2]
Hi...

I have an issue using NumberField, particullary when set the input promput data...

I am assigning the input prompt data, but never it shown... only when set focus to the numberfield and leave it, the input prompt is showed.

```
nfZone = new NumberField();
nfZone.setInputPrompt("ZONE");
nfZone.setDecimalAllowed(false);
nfZone.setGroupingUsed(false);
nfZone.setId("idZone");
nfZone.setDescription("Zone prospected.");
nfZone.setWidth(3, Unit.EM);
nfZone.setImmediate(true);
nfZone.addTextChangeListener(keyPressed);
nfZone.setNegativeAllowed(false);
```

This is the result when open the view...

![numberField](https://cloud.githubusercontent.com/assets/5122581/14481885/c571e5ee-00fc-11e6-952a-4946488d2bfa.png)

After lose focus

![numberField](https://cloud.githubusercontent.com/assets/5122581/14481952/333cad16-00fd-11e6-963c-cb5bb3caed32.png)

**Comment by Ansku** [comment]
Hi!

I don't think the input prompt worked properly in the Vaadin 6 version either, but I agree that it would be nice to have that feature. I've had no time to work on this add-on lately, but I'll add this to my TODO list for when I'm not buried in other work (it's bound to happen some day, I hope...). Pull requests are of course also welcome. Thanks for reporting the issue!
